{"uid":"6e71254fb82c76bc","name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","historyId":"c59643030e1e776644fd5d1d6aa79cfc","time":{"start":1681281247238,"stop":1681281248103,"duration":865},"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"Error: The following error originated from your test code, not from Cypress.\n\n  > undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"package","value":"cypress\\e2e\\gigmSignup.cy.js"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"ef30583078f2da0e","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1681281201971,"stop":1681281202763,"duration":792}},{"uid":"2e5778be0b5e5152","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1681281148708,"stop":1681281149737,"duration":1029}},{"uid":"c2889c32c04ca1da","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1681281103668,"stop":1681281104584,"duration":916}},{"uid":"aa95bdc2590ccf48","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1681281048289,"stop":1681281049692,"duration":1403}},{"uid":"e698368f2fe5bb35","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1681280958820,"stop":1681280962413,"duration":3593}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"6e71254fb82c76bc.json","parameterValues":[]}